project1604: project1604.o readline.o
	gcc -o project1604 project1604.o readline.o
	
project1604.o: project1604.c readline.h
	gcc -c project1604.c

readline.o: readline.c readline.h
	gcc -c readline.c
	
