project1702: project1702.o readline.o
	gcc -o project1702 project1702.o readline.o

project1702.o: project1702.c readline.h
	gcc -c project1702.c

readline.o: readline.c readline.h
	gcc -c readline.c
       
       
