project1703: project1703.o readline.o
	gcc -o project1703 project1703.o readline.o
	
project1703.o: project1703.c readline.h
	gcc -c project1703.c

readline.o: readline.c readline.h
	gcc -c readline.c
	
	
