project1701: project1701.o readline.o
	gcc -o project1701 project1701.o readline.o

project1701.o: project1701.c readline.h
	gcc -c project1701.c

readline.o: readline.c readline.h
	gcc -c readline.c
       
       
