project1602: project1602.o readline.o
	gcc -o project1602 project1602.o readline.o
	
project1602.o: project1602.c readline.h
	gcc -c project1602.c

readline.o: readline.c readline.h
	gcc -c readline.c
	
